### ISSUE TITLE
Installation docs don't mention different base URL for EU

### ISSUE THREAD

**Issue by acton-inger** [pivotal-cf/docs-new-relic-nozzle#13]
Please update these instructions -
https://docs.pivotal.io/partners/new-relic-nozzle/installing.html

- to allow for the possibility that there is another endpoint for EU domains.

You can find the EU New Relic Insights Insert endpoint here:
https://docs.newrelic.com/docs/using-new-relic/welcome-new-relic/getting-started/introduction-eu-region-data-center#endpoints

NOTE: it does not currently include the /v1 path, which is the path that actually works, like so:
insights-collector.eu01.nr-data.net/v1

**Comment by tehall16** [comment]
@acton-inger : Thank you for raising.  New Relic has changed the docs to include information for EU domains.
